#BT
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BOARD_HAS_BT_XPAN  ?= true

#FM
BOARD_HAVE_QCOM_FM ?= false

ifeq ($(TARGET_USES_QMAA),true)
ifneq ($(TARGET_USES_QMAA_OVERRIDE_BLUETOOTH),true)
BOARD_ANT_WIRELESS_DEVICE :=
endif
ifneq ($(TARGET_USES_QMAA_OVERRIDE_FM),true)
BOARD_HAVE_QCOM_FM := false
endif
endif
